// Product database - shared across the application
export const productDatabase = {
  1: {
    id: 1,
    name: "Esprit Ruffle Shirt",
    price: "16.64",
    originalPrice: "24.99",
    discount: 33,
    images: [
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=1000&fit=crop&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop&q=80",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=1000&fit=crop&q=80",
    ],
    category: "Women",
    color: "white",
    colors: ["white", "black", "blue", "pink"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["Fashion", "Lifestyle"],
    rating: 4.5,
    reviews: 128,
    inStock: true,
    stock: 15,
    description:
      "Elevate your wardrobe with this elegant ruffle shirt from Esprit. Made from premium cotton blend, this shirt features delicate ruffled details that add a touch of sophistication to any outfit. Perfect for both casual and formal occasions.",
    features: [
      "100% Premium Cotton Blend",
      "Machine Washable",
      "Wrinkle Resistant",
      "Comfortable Fit",
      "Available in Multiple Colors",
    ],
    shipping:
      "Free shipping on orders over $50. Standard delivery: 3-5 business days.",
    returnPolicy:
      "30-day return policy. Items must be unworn and in original condition.",
  },
  2: {
    id: 2,
    name: "Herschel supply",
    price: "35.31",
    originalPrice: "45.00",
    discount: 22,
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&h=1000&fit=crop&q=80",
    ],
    category: "Women",
    color: "white",
    colors: ["white", "black", "gray"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["Fashion", "Streetstyle"],
    rating: 4.2,
    reviews: 89,
    inStock: true,
    stock: 8,
    description:
      "Stylish and comfortable supply from Herschel. This versatile piece combines modern design with classic comfort, making it a must-have in your collection.",
    features: [
      "Premium Quality Material",
      "Comfortable Fit",
      "Modern Design",
      "Easy Care",
    ],
    shipping: "Free shipping on orders over $50.",
    returnPolicy: "30-day return policy.",
  },
  3: {
    id: 3,
    name: "Only Check Trouser",
    price: "25.50",
    images: [
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&h=1000&fit=crop&q=80",
    ],
    category: "Men",
    color: "blue",
    colors: ["blue", "black", "gray"],
    sizes: ["28", "30", "32", "34", "36"],
    tags: ["Denim", "Streetstyle"],
    rating: 4.7,
    reviews: 156,
    inStock: true,
    stock: 12,
    description:
      "Classic check pattern trousers that never go out of style. Perfect for both casual and smart-casual looks.",
    features: ["Classic Check Pattern", "Comfortable Fit", "Durable"],
    shipping: "Free shipping available.",
    returnPolicy: "30-day return policy.",
  },
  4: {
    id: 4,
    name: "Classic Trench Coat",
    price: "75.00",
    images: [
      "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&h=1000&fit=crop&q=80",
    ],
    category: "Women",
    color: "green",
    colors: ["green", "beige", "black"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["Fashion", "Lifestyle"],
    rating: 4.8,
    reviews: 203,
    inStock: true,
    stock: 5,
    description:
      "Timeless trench coat that combines elegance with functionality. Perfect for all seasons.",
    features: ["Water Resistant", "Classic Design", "Premium Material"],
    shipping: "Free shipping on orders over $50.",
    returnPolicy: "30-day return policy.",
  },
  5: {
    id: 5,
    name: "Denim Jacket",
    price: "45.00",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1000&fit=crop&q=80",
    ],
    category: "Men",
    color: "blue",
    colors: ["blue", "black", "gray"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Denim", "Streetstyle"],
    rating: 4.6,
    reviews: 142,
    inStock: true,
    stock: 10,
    description:
      "Classic denim jacket with modern fit. Perfect for layering and adding a casual edge to any outfit.",
    features: ["100% Cotton Denim", "Classic Fit", "Durable Construction"],
    shipping: "Free shipping on orders over $50.",
    returnPolicy: "30-day return policy.",
  },
  6: {
    id: 6,
    name: "Leather Bag",
    price: "55.00",
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=1000&fit=crop&q=80",
    ],
    category: "Bag",
    color: "black",
    colors: ["black", "brown", "tan"],
    sizes: ["One Size"],
    tags: ["Fashion", "Crafts"],
    rating: 4.4,
    reviews: 98,
    inStock: true,
    stock: 7,
    description:
      "Premium leather bag with spacious interior and multiple compartments. Perfect for everyday use.",
    features: ["Genuine Leather", "Multiple Compartments", "Adjustable Strap"],
    shipping: "Free shipping on orders over $50.",
    returnPolicy: "30-day return policy.",
  },
  7: {
    id: 7,
    name: "Running Shoes",
    price: "89.99",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=1000&fit=crop&q=80",
    ],
    category: "Shoes",
    color: "black",
    colors: ["black", "white", "gray", "blue"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    tags: ["Lifestyle", "Streetstyle"],
    rating: 4.9,
    reviews: 267,
    inStock: true,
    stock: 20,
    description:
      "High-performance running shoes with advanced cushioning and breathable mesh upper. Designed for comfort and durability.",
    features: [
      "Breathable Mesh",
      "Advanced Cushioning",
      "Durable Outsole",
      "Lightweight",
    ],
    shipping: "Free shipping on orders over $50.",
    returnPolicy: "30-day return policy.",
  },
  8: {
    id: 8,
    name: "Classic Watch",
    price: "120.00",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=1000&fit=crop&q=80",
    ],
    category: "Watches",
    color: "black",
    colors: ["black", "silver", "gold"],
    sizes: ["One Size"],
    tags: ["Fashion", "Lifestyle"],
    rating: 4.7,
    reviews: 189,
    inStock: true,
    stock: 12,
    description:
      "Elegant classic watch with precision movement and timeless design. Perfect for both formal and casual occasions.",
    features: [
      "Precision Movement",
      "Water Resistant",
      "Leather Strap",
      "Classic Design",
    ],
    shipping: "Free shipping on orders over $50.",
    returnPolicy: "30-day return policy.",
  },
};
