import { Suspense } from "react";
import { ConfigProvider } from "antd";
import "./globals.css";
import { Nav } from "@/components/Header/Nav";
import AdminAccessNotice from "@/components/AdminAccessNotice";
import ConditionalFooter from "@/components/ConditionalFooter";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { ThemeProvider } from "@/context/ThemeContext";
import { AuthProvider } from "@/context/AuthContext";
import { CustomDesignProvider } from "@/context/CustomDesignContext";
import AppToasterShell from "@/components/providers/AppToasterShell";
import RouteGuard from "@/components/RouteGuard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const savedTheme = localStorage.getItem('theme');
                if (savedTheme !== 'dark') {
                  document.documentElement.classList.remove('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body
        className="antialiased"
        suppressHydrationWarning
      >
        <ConfigProvider theme={{ token: { colorPrimary: '#1e9a58' } }}>
          <ThemeProvider>
            <AuthProvider>
              <AppToasterShell />
              <Suspense fallback={null}>
                <AdminAccessNotice />
              </Suspense>
              <CustomDesignProvider>
                <CartProvider>
                  <WishlistProvider>
                    <RouteGuard>
                      <Nav />
                      {children}
                      <ConditionalFooter />
                    </RouteGuard>
                  </WishlistProvider>
                </CartProvider>
              </CustomDesignProvider>
            </AuthProvider>
          </ThemeProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
