"use client";
import React, { useState, useEffect, useCallback } from "react";
import axios from "axios";
import {
  Card,
  Select,
  Row,
  Col,
  Statistic,
  Table,
  Tag,
  message,
  Descriptions,
  Button,
  Modal,
  Input,
} from "antd";
import { IconShieldExclamation, IconCheck } from "@tabler/icons-react";
import { formatPrice } from "@/lib/formatPrice";

const { TextArea } = Input;

const authHeaders = () => ({
  Authorization: `Bearer ${localStorage.getItem("token")}`,
  "Content-Type": "application/json",
});

const severityColor = { critical: "red", high: "volcano", medium: "orange", low: "gold" };

const statusColor = {
  pending: "default",
  reviewed: "blue",
  resolved: "green",
  "false-positive": "purple",
};

// Matches the 5 patterns actually generated by
// /api/admin/finance/fraud-detection — kept as a literal map (rather than
// deriving from the type string) so a label change there doesn't need a
// matching change here, and vice versa.
const TYPE_LABELS = {
  high_value_new_user: "High-value order, new account",
  rapid_cancellation: "Rapid cancellation pattern",
  multiple_payment_methods: "Multiple payment methods used",
  suspicious_refund_pattern: "Suspicious refund pattern",
  address_mismatch: "Billing/shipping address mismatch",
};

const REVIEW_ACTIONS = [
  { status: "reviewed", label: "Mark Reviewed" },
  { status: "resolved", label: "Resolve" },
  { status: "false-positive", label: "False Positive" },
];

const FraudDetection = () => {
  const [severity, setSeverity] = useState(undefined);
  const [status, setStatus] = useState(undefined);
  const [loading, setLoading] = useState(false);
  const [alerts, setAlerts] = useState([]);
  const [stats, setStats] = useState(null);
  const [reviewTarget, setReviewTarget] = useState(null); // { alert, status }
  const [notes, setNotes] = useState("");
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await axios.get("/api/admin/finance/fraud-detection", {
        params: { severity, status, limit: 100 },
        headers: authHeaders(),
      });
      if (!data?.success) throw new Error(data?.message);
      setAlerts(data.data.alerts || []);
      setStats(data.data.statistics);
    } catch (error) {
      message.error(
        error.response?.data?.message || "Failed to load fraud detection alerts"
      );
    } finally {
      setLoading(false);
    }
  }, [severity, status]);

  useEffect(() => {
    load();
  }, [load]);

  const openReviewModal = (alert, targetStatus) => {
    setReviewTarget({ alert, status: targetStatus });
    setNotes(alert.review?.notes || "");
  };

  const submitReview = async () => {
    if (!reviewTarget) return;
    setSaving(true);
    try {
      const { data } = await axios.post(
        "/api/admin/finance/fraud-detection/review",
        { alertId: reviewTarget.alert.id, status: reviewTarget.status, notes },
        { headers: authHeaders() }
      );
      if (!data?.success) throw new Error(data?.message);
      message.success("Alert updated");
      setReviewTarget(null);
      load();
    } catch (error) {
      message.error(error.response?.data?.message || "Failed to update alert");
    } finally {
      setSaving(false);
    }
  };

  const columns = [
    {
      title: "Severity",
      dataIndex: "severity",
      width: 100,
      render: (v) => (
        <Tag color={severityColor[v] || "default"} className="capitalize">
          {v}
        </Tag>
      ),
    },
    {
      title: "Alert",
      dataIndex: "title",
      render: (v, r) => (
        <div>
          <div className="font-medium">{v}</div>
          <div className="text-xs text-gray-500">{TYPE_LABELS[r.type] || r.type}</div>
        </div>
      ),
    },
    { title: "Description", dataIndex: "description" },
    {
      title: "Status",
      dataIndex: "status",
      width: 130,
      render: (v, r) => (
        <div>
          <Tag color={statusColor[v] || "default"} className="capitalize">
            {v.replace("-", " ")}
          </Tag>
          {r.review?.reviewedBy && (
            <div className="text-[10px] text-gray-500 mt-1">
              by {r.review.reviewedBy.name}
            </div>
          )}
        </div>
      ),
    },
    {
      title: "Detected",
      dataIndex: "detectedAt",
      width: 160,
      render: (v) => new Date(v).toLocaleString(),
    },
    {
      title: "Actions",
      width: 260,
      render: (_, r) => (
        <div className="flex flex-wrap gap-1.5">
          {REVIEW_ACTIONS.filter((a) => a.status !== r.status).map((a) => (
            <Button
              key={a.status}
              size="small"
              icon={a.status === "resolved" ? <IconCheck className="w-3.5 h-3.5" /> : undefined}
              onClick={() => openReviewModal(r, a.status)}
            >
              {a.label}
            </Button>
          ))}
        </div>
      ),
    },
  ];

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-3 justify-between">
        <div className="flex flex-wrap gap-3">
          <Select
            allowClear
            placeholder="All severities"
            value={severity}
            onChange={setSeverity}
            style={{ width: 170 }}
            options={["critical", "high", "medium", "low"].map((s) => ({
              value: s,
              label: s.charAt(0).toUpperCase() + s.slice(1),
            }))}
          />
          <Select
            allowClear
            placeholder="All statuses"
            value={status}
            onChange={setStatus}
            style={{ width: 170 }}
            options={["pending", "reviewed", "resolved", "false-positive"].map((s) => ({
              value: s,
              label: s.charAt(0).toUpperCase() + s.slice(1).replace("-", " "),
            }))}
          />
        </div>
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <IconShieldExclamation className="w-4 h-4" />
          Computed live from order patterns — decisions you record are saved and persist across refreshes
        </div>
      </div>

      {stats && (
        <Row gutter={[16, 16]}>
          <Col xs={12} md={6}>
            <Card size="small">
              <Statistic title="Total Alerts" value={stats.total} />
            </Card>
          </Col>
          <Col xs={12} md={6}>
            <Card size="small">
              <Statistic
                title="Critical"
                value={stats.bySeverity.critical}
                valueStyle={{ color: "#cf1322" }}
              />
            </Card>
          </Col>
          <Col xs={12} md={6}>
            <Card size="small">
              <Statistic
                title="High"
                value={stats.bySeverity.high}
                valueStyle={{ color: "#d4380d" }}
              />
            </Card>
          </Col>
          <Col xs={12} md={6}>
            <Card size="small">
              <Statistic title="Pending Review" value={stats.byStatus?.pending ?? 0} />
            </Card>
          </Col>
        </Row>
      )}

      <Card>
        <Table
          rowKey="id"
          columns={columns}
          dataSource={alerts}
          loading={loading}
          pagination={{ pageSize: 10 }}
          expandable={{
            expandedRowRender: (r) => (
              <div className="space-y-3">
                <Descriptions size="small" column={2} bordered>
                  {Object.entries(r.details || {}).map(([k, v]) => (
                    <Descriptions.Item key={k} label={k}>
                      {Array.isArray(v)
                        ? v.length
                        : typeof v === "number" && /amount|total/i.test(k)
                          ? `₹${formatPrice(v)}`
                          : String(v)}
                    </Descriptions.Item>
                  ))}
                </Descriptions>
                {r.review?.notes && (
                  <div className="text-xs bg-zinc-900 border border-zinc-800 rounded-lg p-2.5">
                    <span className="text-gray-400">Review notes: </span>
                    {r.review.notes}
                  </div>
                )}
              </div>
            ),
          }}
        />
      </Card>

      <Modal
        title={reviewTarget ? REVIEW_ACTIONS.find((a) => a.status === reviewTarget.status)?.label : ""}
        open={!!reviewTarget}
        onCancel={() => setReviewTarget(null)}
        onOk={submitReview}
        confirmLoading={saving}
        okText="Save"
      >
        <p className="text-sm text-gray-500 mb-3">{reviewTarget?.alert?.title}</p>
        <TextArea
          rows={4}
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Optional notes about this decision…"
          maxLength={1000}
        />
      </Modal>
    </div>
  );
};

export default FraudDetection;
