"use client";
import React, { useState, useEffect, useCallback, useMemo } from "react";
import axios from "axios";
import {
  Card,
  Select,
  Row,
  Col,
  Statistic,
  Tag,
  message,
  Descriptions,
  Button,
  Modal,
  Input,
} from "antd";
import { IconShieldExclamation, IconCheck, IconEye } from "@tabler/icons-react";
import { formatPrice } from "@/lib/formatPrice";
import { AgGridReact } from "ag-grid-react";
import {
  ModuleRegistry,
  AllCommunityModule,
  themeQuartz,
  colorSchemeDark,
} from "ag-grid-community";

ModuleRegistry.registerModules([AllCommunityModule]);
const myDarkTheme = themeQuartz.withPart(colorSchemeDark).withParams({
  backgroundColor: "#09090b",
  foregroundColor: "#e4e4e7",
  headerBackgroundColor: "#18181b",
  borderColor: "#27272a",
  rowHoverColor: "#18181b",
});

const { TextArea } = Input;

const authHeaders = () => ({
  Authorization: `Bearer ${localStorage.getItem("token")}`,
  "Content-Type": "application/json",
});

const severityColor = { critical: "red", high: "volcano", medium: "orange", low: "gold" };

const statusColor = {
  pending: "default",
  reviewed: "blue",
  resolved: "green",
  "false-positive": "purple",
};

// Matches the 5 patterns actually generated by
// /api/admin/finance/fraud-detection — kept as a literal map (rather than
// deriving from the type string) so a label change there doesn't need a
// matching change here, and vice versa.
const TYPE_LABELS = {
  high_value_new_user: "High-value order, new account",
  rapid_cancellation: "Rapid cancellation pattern",
  multiple_payment_methods: "Multiple payment methods used",
  suspicious_refund_pattern: "Suspicious refund pattern",
  address_mismatch: "Billing/shipping address mismatch",
};

const REVIEW_ACTIONS = [
  { status: "reviewed", label: "Mark Reviewed" },
  { status: "resolved", label: "Resolve" },
  { status: "false-positive", label: "False Positive" },
];

const FraudDetection = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    const id = setTimeout(() => setIsClient(true), 0);
    return () => clearTimeout(id);
  }, []);
  const [severity, setSeverity] = useState(undefined);
  const [status, setStatus] = useState(undefined);
  const [loading, setLoading] = useState(false);
  const [alerts, setAlerts] = useState([]);
  const [stats, setStats] = useState(null);
  const [reviewTarget, setReviewTarget] = useState(null); // { alert, status }
  const [notes, setNotes] = useState("");
  const [saving, setSaving] = useState(false);
  const [detailsTarget, setDetailsTarget] = useState(null); // alert whose details are shown

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await axios.get("/api/admin/finance/fraud-detection", {
        params: { severity, status, limit: 100 },
        headers: authHeaders(),
      });
      if (!data?.success) throw new Error(data?.message);
      setAlerts(data.data.alerts || []);
      setStats(data.data.statistics);
    } catch (error) {
      message.error(
        error.response?.data?.message || "Failed to load fraud detection alerts"
      );
    } finally {
      setLoading(false);
    }
  }, [severity, status]);

  useEffect(() => {
    load();
  }, [load]);

  const openReviewModal = (alert, targetStatus) => {
    setReviewTarget({ alert, status: targetStatus });
    setNotes(alert.review?.notes || "");
  };

  const submitReview = async () => {
    if (!reviewTarget) return;
    setSaving(true);
    try {
      const { data } = await axios.post(
        "/api/admin/finance/fraud-detection/review",
        { alertId: reviewTarget.alert.id, status: reviewTarget.status, notes },
        { headers: authHeaders() }
      );
      if (!data?.success) throw new Error(data?.message);
      message.success("Alert updated");
      setReviewTarget(null);
      load();
    } catch (error) {
      message.error(error.response?.data?.message || "Failed to update alert");
    } finally {
      setSaving(false);
    }
  };

  const columnDefs = useMemo(
    () => [
      {
        headerName: "Severity",
        field: "severity",
        width: 110,
        cellRenderer: (p) => (
          <Tag color={severityColor[p.value] || "default"} className="capitalize">
            {p.value}
          </Tag>
        ),
      },
      {
        headerName: "Alert",
        field: "title",
        flex: 1,
        minWidth: 180,
        cellRenderer: (p) => (
          <div className="h-full flex flex-col justify-center">
            <div className="font-medium">{p.value}</div>
            <div className="text-xs text-gray-500">
              {TYPE_LABELS[p.data.type] || p.data.type}
            </div>
          </div>
        ),
      },
      {
        headerName: "Description",
        field: "description",
        flex: 1,
        minWidth: 200,
      },
      {
        headerName: "Status",
        field: "status",
        width: 140,
        cellRenderer: (p) => (
          <div className="h-full flex flex-col justify-center">
            <Tag color={statusColor[p.value] || "default"} className="capitalize">
              {p.value.replace("-", " ")}
            </Tag>
            {p.data.review?.reviewedBy && (
              <div className="text-[10px] text-gray-500 mt-1">
                by {p.data.review.reviewedBy.name}
              </div>
            )}
          </div>
        ),
      },
      {
        headerName: "Detected",
        field: "detectedAt",
        width: 170,
        cellRenderer: (p) => new Date(p.value).toLocaleString(),
      },
      {
        headerName: "Actions",
        width: 320,
        pinned: "right",
        cellRenderer: (p) => {
          const r = p.data;
          return (
            <div className="h-full flex flex-wrap items-center gap-1.5">
              <Button
                size="small"
                icon={<IconEye className="w-3.5 h-3.5" />}
                onClick={() => setDetailsTarget(r)}
              >
                Details
              </Button>
              {REVIEW_ACTIONS.filter((a) => a.status !== r.status).map((a) => (
                <Button
                  key={a.status}
                  size="small"
                  icon={a.status === "resolved" ? <IconCheck className="w-3.5 h-3.5" /> : undefined}
                  onClick={() => openReviewModal(r, a.status)}
                >
                  {a.label}
                </Button>
              ))}
            </div>
          );
        },
      },
    ],
    []
  );

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-3 justify-between">
        <div className="flex flex-wrap gap-3">
          <Select
            allowClear
            placeholder="All severities"
            value={severity}
            onChange={setSeverity}
            style={{ width: 170 }}
            options={["critical", "high", "medium", "low"].map((s) => ({
              value: s,
              label: s.charAt(0).toUpperCase() + s.slice(1),
            }))}
          />
          <Select
            allowClear
            placeholder="All statuses"
            value={status}
            onChange={setStatus}
            style={{ width: 170 }}
            options={["pending", "reviewed", "resolved", "false-positive"].map((s) => ({
              value: s,
              label: s.charAt(0).toUpperCase() + s.slice(1).replace("-", " "),
            }))}
          />
        </div>
        <div className="flex items-center gap-2 text-xs text-gray-500">
          <IconShieldExclamation className="w-4 h-4" />
          Computed live from order patterns — decisions you record are saved and persist across refreshes
        </div>
      </div>

      {stats && (
        <Row gutter={[16, 16]}>
          <Col xs={12} md={6}>
            <Card size="small">
              <Statistic title="Total Alerts" value={stats.total} />
            </Card>
          </Col>
          <Col xs={12} md={6}>
            <Card size="small">
              <Statistic
                title="Critical"
                value={stats.bySeverity.critical}
                valueStyle={{ color: "#cf1322" }}
              />
            </Card>
          </Col>
          <Col xs={12} md={6}>
            <Card size="small">
              <Statistic
                title="High"
                value={stats.bySeverity.high}
                valueStyle={{ color: "#d4380d" }}
              />
            </Card>
          </Col>
          <Col xs={12} md={6}>
            <Card size="small">
              <Statistic title="Pending Review" value={stats.byStatus?.pending ?? 0} />
            </Card>
          </Col>
        </Row>
      )}

      <Card>
        {isClient ? (
          <div style={{ width: "100%", height: 560 }}>
            <AgGridReact
              theme={myDarkTheme}
              modules={[AllCommunityModule]}
              rowData={alerts}
              columnDefs={columnDefs}
              defaultColDef={{ sortable: true, resizable: true }}
              getRowId={(p) => String(p.data.id)}
              animateRows
              rowHeight={64}
              headerHeight={44}
              loading={loading}
              suppressCellFocus
              overlayNoRowsTemplate="No fraud alerts found"
            />
          </div>
        ) : (
          <div className="h-[560px]" />
        )}
      </Card>

      {/* Alert Details Modal — replaces the antd Table's inline expandable
          row (not available in AG Grid Community) with an equivalent
          on-demand details view. */}
      <Modal
        title={detailsTarget?.title}
        open={!!detailsTarget}
        onCancel={() => setDetailsTarget(null)}
        footer={[
          <Button key="close" onClick={() => setDetailsTarget(null)}>
            Close
          </Button>,
        ]}
      >
        {detailsTarget && (
          <div className="space-y-3">
            <Descriptions size="small" column={2} bordered>
              {Object.entries(detailsTarget.details || {}).map(([k, v]) => (
                <Descriptions.Item key={k} label={k}>
                  {Array.isArray(v)
                    ? v.length
                    : typeof v === "number" && /amount|total/i.test(k)
                      ? `₹${formatPrice(v)}`
                      : String(v)}
                </Descriptions.Item>
              ))}
            </Descriptions>
            {detailsTarget.review?.notes && (
              <div className="text-xs bg-zinc-900 border border-zinc-800 rounded-lg p-2.5">
                <span className="text-gray-400">Review notes: </span>
                {detailsTarget.review.notes}
              </div>
            )}
          </div>
        )}
      </Modal>

      <Modal
        title={reviewTarget ? REVIEW_ACTIONS.find((a) => a.status === reviewTarget.status)?.label : ""}
        open={!!reviewTarget}
        onCancel={() => setReviewTarget(null)}
        onOk={submitReview}
        confirmLoading={saving}
        okText="Save"
      >
        <p className="text-sm text-gray-500 mb-3">{reviewTarget?.alert?.title}</p>
        <TextArea
          rows={4}
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Optional notes about this decision…"
          maxLength={1000}
        />
      </Modal>
    </div>
  );
};

export default FraudDetection;
